### ISSUE TITLE
Loading boards

### ISSUE THREAD

**Issue by GabrielPereyra** [aprescott/tenuki#32]
Is there a way to start from an existing board instead of from an empty board?

**Comment by aprescott** [comment]
There's currently no direct way of loading a board as the starting point, although I do have plans to support this sort of thing.

Since Tenuki is currently based around playing games, there's no way to set an arbitrary board state, so the way to do this for now is to call `playAt` with a move sequence:

```js
existingMoves.forEach(([y, x]) => {
  game.playAt(y, x);
});
```

There's obviously an assumption here that `existingMoves` doesn't contain invalid moves for the ruleset `game` is set up with. If that's a concern you can verify the return values of `playAt`.

For more context, in the future, I can imagine the possibility of defining an entire starting board state without the move history, against which you'd play. However, that's not quite the same as playing a "game", and is more like general board editing functionality. The reason it isn't like playing a game is that, e.g., superko rule checking isn't possible without the entire move history: if you don't know the previous positions, a move's validity may be wrong.

Within a "play a game" context, it's important to consider it as loading _move history_ in some way, not just a single board state. In contexts where you're editing a board and playing in a move-like way (alternating stones, but without full rule enforcement), then "start at board state X" is easier. That's future work, though.

Hopefully the `playAt` method works for you, but feel free to point out any problems with it!

**Comment by yangboz** [comment]
even more  on supporting load *.sgf file?

**Comment by aprescott** [comment]
Similar plans to support SGF, yes. In the meantime it should be possible to load an SGF file with any other library and then write some simple glue code to load the main tree into a sequence of moves.

**Comment by aprescott** [comment]
Since I've hopefully addressed the question, I'm going to close this issue.
