### ISSUE TITLE
Built js file references `./lib/` everywhere

### ISSUE THREAD

**Issue by maackle** [aprescott/tenuki#37]
The built JS file is not standalone - it requires `./lib/` to be present, which makes it difficult to work with in a static webpage. (See the first 15 lines of `build/tenuki.js`)

Moreover, the last two releases (0.2.2 and 0.2.1) don't include `build` and/or `lib` directories.

**Comment by aprescott** [comment]
Can you provide an example of the issue you're encountering? Does standalone use not work for you? How does it fail? I can't reproduce the problem, and everything looks right to me.

The references to `./lib/` in `build/tenuki.js` shouldn't cause it to not work standalone. They're labels into other modules defined in the rest of the file. For example, below the first 3 `require` calls:

```js
},{"./lib/client":3,"./lib/game":6,"./lib/utils":14}],2:[function(require,module,exports){
```

The [built file is generated via `make build` and uses Browserify's `--standalone` option](https://github.com/aprescott/tenuki/blob/5b1f28baf6ece606ab4bb13e1d44207d5b15551c/Makefile#L26).

Locally, I can reproduce a working example:

```shell
$ make clean
rm -rf build tmp lib
$ make all
mkdir -p lib
mkdir -p tmp/output-css
mkdir -p build
babel \
		--source-maps \
		--presets es2015 \
		--out-file lib/board-state.js \
		src/board-state.js
[...]
cat copyright_header.txt \
		<(cat tmp/output-css/*.css | cleancss) \
		> build/tenuki.min.css
$ echo '<!doctype html><link rel="stylesheet" type="text/css" href="build/tenuki.css"><script src="build/tenuki.js"></script><div class="tenuki-board"></div><script>var boardElement = document.querySelector(".tenuki-board");var game = new tenuki.Game({ element: boardElement });</script>' > sample.html

# now open sample.html in a browser
```

The live examples linked in the README also use the standalone `build/` files and they seem to work as expected: https://aprescott.github.io/tenuki/examples/example.html.

Finally, the `build/` and `lib/` directories are sadly not currently included in the tag-based GitHub releases because the releases are generated automatically from git tags. Since `build/` and `lib/` files aren't in source code, they're not in the tarballs GitHub generates. I would like to have a cleaner way of managing release artifacts (there are 2 distinct build targets), but for now the expectation is that you'd run `make build` on the versioned source. I will try to update the README to reflect what's currently expected.

**Comment by aprescott** [comment]
(Minor typo in my comment: `make all` is the command, not `make build`.)

**Comment by maackle** [comment]
Sorry, I was tired when I wrote this, and course you're right about the `require(./lib/*)`!

Even though I misdiagnosed the problem, I raised this issue because I'm still having trouble getting a board to render, even though there are no JS errors. Which is a separate problem that I'll look into, but I'll mention it here.

When I create a simple html file that seems to follow your example exactly (but with my own tenuki.[css|js] files that I got from `make all`), the board does not render. Here's the file:

```html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" type="text/css" href="vendor/tenuki/tenuki.css" />
  <script type="text/javascript" src="vendor/tenuki/tenuki.js"></script>
</head>
<body>
  <div class="tenuki-board"></div>

  <script type="text/javascript">
    const boardElement = document.querySelector(".tenuki-board");
    const game = new tenuki.Game({
      element: boardElement,
      boardSize: 19,
    });
  </script>
</body>
</html>
```

When I try `game.setup()` I get "Uncaught TypeError: boardElement.hasAttribute is not a function"

When I try `game.render()` I get "Uncaught TypeError: Cannot read property 'render' of undefined"

Seems that the renderer is not being set up properly? Can you see what the problem could be?

**Comment by aprescott** [comment]
@maackle I suspect you're using 0.2.2, and not the latest `master` from the repo. There were changes in 8079c7cb260271323666570f2c5ba8fa5b641552 to the way setup works. In 0.2.2, the setup used the old way of passing a board element as the first argument. Try this:

```js
const game = new tenuki.Game(boardElement);
game.setup(); // still required in 0.2.2
```

I should definitely cut a 0.3.0 release, since this is confusing. :) I dropped `game.setup()` in the new version because it's not a great API.

**Comment by maackle** [comment]
Yes I'm using 0.2.2, and that does the trick! Yes, please consider cutting a new release! :) I followed the examples not knowing that they had breaking changes relative to the latest release.

Would you say master is stable enough to start using or should I continue to use 0.2.2?

**Comment by aprescott** [comment]
I would use `master` if you can. 0.2.2 suffers from some performance problems, among other things. There are a couple of bugs in the game engine for equivalence scoring in `master`, because of a misinterpretation of AGA rules (e.g., handicap stones and scoring, and how to end the game) but otherwise it's definitely more stable than 0.2.2.

**Comment by maackle** [comment]
Gotcha, will do 👍  thanks for the quick help!
