### ISSUE TITLE
Do you know KataGo and WGo.js? Why repeat work？

### ISSUE THREAD

**Issue by HackYardo** [aprescott/tenuki#47]
KataGo is a Go-playing AI after AlphaGo and it has a [rule set](https://lightvector.github.io/KataGo/rules.html) that supports almost all rules of Go.
[WGo.js](http://www.wgo.waltheri.net/) is a JavaScript Go library that can plot Go boards and manage Go games. 
It looks like you repeat those work which some other people have done several years ago.

**Comment by aprescott** [comment]
KataGo is a trained AI engine, whereas Tenuki is not. While both may implement ruleset functionality, they are different tools with different uses.

WGo does indeed have very similar goals. You should use it if it's suitable! Likewise for any of the other similar projects that exist.

> Why repeat work？

Well, why does anyone release software that exists already in some form? :) The short version is that I wanted to and it was fun.

If you're asking because you're curious about original motivations...

I was a bit dissatisfied with existing board implementations, since they used HTML `<canvas>` or raster images for their boards. Bitmaps don't have a great mobile experience: the board is so big that you have to constantly zoom in and out a lot to do anything (you need to both analyze small sections of the board but also get a complete overview), but this can cause blurry images. You also encounter all sorts of issues related to dragging/panning the board itself without placing a stone. Worse, the board engine might calculate the completely wrong position for a play, depending on how the calculation is done with respect to the browser viewport.

AlphaGo was new at the time, and it troubled me a little that beginner players would try to learn the game on their phones, then immediately run into a pretty awkward experience. So I was curious what the limits of a more mobile-friendly implementation looked like. (I'm not trying to slight other projects that use bitmap boards. They inherit an environment of desktop-only browsers and, in some cases, Macromedia/Flash.) I'm obviously biased but I think Tenuki handles these things fairly well.

Anyhow, I don't exactly know what the current landscape is like with mobile UX. But again, people should use whichever software they think makes sense for them. If Tenuki only ever exists as an example of one approach to some set of problems, that's fine.

**Comment by joshbotnet** [comment]
Hey @aprescott Tenuki is a brilliant, super-clean implementation.

I compared widely and selected it for integration in a Svelte app _in 2025_ 

amazing work - thank you xx
